### ISSUE TITLE
facebook sdk lags behind one version

### ISSUE THREAD

**Issue by Kampfbereit** [thomaswelton/laravel-facebook#6]
thomaswelton / facebook-php-sdk v.3.2.2,
official facebook is at version v.3.2.3.

**Comment by thomaswelton** [comment]
I have updated that package https://github.com/thomaswelton/facebook-php-sdk/releases/tag/v3.2.3

Run a composer update. You should get it. Please me let know if this all works for you as I've only done brief testing over my lunch hour.

**Comment by Kampfbereit** [comment]
Seems to work fine here! Thanks.

**Comment by thomaswelton** [comment]
Awesome, thanks.
